### ISSUE TITLE
PostCSS Not Being Used?

### ISSUE THREAD

**Issue by jednano** [glenjamin/ultimate-hot-reloading-example#12]
I see postcss dependencies, but I don't see anywhere it's being used or even referenced in the README. Am I missing something?

**Comment by glenjamin** [comment]
I think they are peer dependencies of the CSS Modules stuff.

**Comment by jednano** [comment]
Aha! You're right! See [here](https://github.com/css-modules/css-modules-require-hook/blob/master/package.json#L45-L51); however, is there not a way to pass a custom PostCSS configuration to this loader? I have a very customized PostCSS config, as most would, I think.

**Comment by glenjamin** [comment]
I would hope there is, but this isn't something I'm familiar with. You might find something useful on the CSS modules docs or the webpack CSS loader
