### ISSUE TITLE
Express routes not reloading

### ISSUE THREAD

**Issue by siegesmund** [glenjamin/ultimate-hot-reloading-example#16]
Not sure if I'm missing something but the express routes aren't reloading. On Mac OS 10.11, and have tried running the example in Chrome, Firefox and on node.js versions 0.12.9, 4.3.1 & 5.

**Comment by glenjamin** [comment]
Do you ever see the log output from this line? https://github.com/glenjamin/ultimate-hot-reloading-example/blob/master/server.js#L41

**Comment by siegesmund** [comment]
Yes, it prints out each time I save server/app.js

**Comment by glenjamin** [comment]
but after that the route changes still don't take effect?

**Comment by siegesmund** [comment]
That's right. There's no update to the page. I have to manually refresh the page to see the change.

**Comment by glenjamin** [comment]
Oh, you'll always need to refresh to see the change on a server rendered page. That feature is intended for API routes and things.

The client-side javascript pages are the ones which automatically hot update.

**Comment by siegesmund** [comment]
Oh, ok, I misunderstood the intent of the feature. Thanks!

**Comment by siegesmund** [comment]
Also, thanks for sharing this repo. Simple but powerful.
