### ISSUE TITLE
Working on Koa2?

### ISSUE THREAD

**Issue by 0cv** [glenjamin/ultimate-hot-reloading-example#17]
I've tried to take the snippet of code https://github.com/glenjamin/ultimate-hot-reloading-example/blob/master/server.js#L37#L46 and to move it into my Koa2 server. I can see a large list of entries in require.cache, and when a file is saved, the require.cache is cleaned accordingly (just the ones from the /server). Yet, when I reload the page, the require.cache is not updated, and more strangely the application continues to work just normally. I've even tried to delete all keys from require.cache and this does nothing. Koa2 is in some way relatively similar to Express, at least I would expect when it comes to require.cache, and I'm wondering just why this does not seem to work. I'm actually even more surprised that my app continues to work even so the require.cache is cleaned. I know this plugin is not about Koa2, but maybe someone has some ideas?

**Comment by glenjamin** [comment]
The other part that makes it work is doing a `require` inside the main HTTP handler. Can you post a sample?

**Comment by 0cv** [comment]
I have added that in the server part:

``` js
const watcher = chokidar.watch(`${__dirname}/..`);

watcher.on('ready', function() {
  watcher.on('all', function() {
    console.log('Clearing /server/ module cache from server');
    Object.keys(require.cache).forEach(function(id) {
      if (/[\/\\]server[\/\\]/.test(id) && !(/[\/\\]bin[\/\\]/.test(id)) && !(/[\/\\]models[\/\\]/.test(id))) {
        console.log('delete', id)
        delete require.cache[id]
        require(id)
      }
    });
  });
});
```

=> I exclude the bin folder where the server is located, also the models, because mongoose complains when the model is recreated twice, fair enough.

I have also added explicitly a require(id) after deleting from the cache, otherwise the next time it's run, somehow, the modules are not required again (could be already one problem why I need to do that...)

I should mention I'm using babel with babel-register and ES6 import/export. I've seen, they are somehow caching modules too http://babeljs.io/docs/usage/require/, but I've disabled the cache like mentioned (I have also tried to delete the json file created to force a refresh). Both options didn't change anything.

Below is the structure of the server folder where we can see the bin folder and models folder (both ignored):
![image](https://cloud.githubusercontent.com/assets/1253866/15570093/92589842-2334-11e6-9caa-818cc5bee67b.png)

For my tests, I changed the value in the console.log and then refreshed the browser to trigger the route. The value shown in the console is (of course) correct the first time the app is started, but not for any subsequent edit to the console.log.

**Comment by glenjamin** [comment]
I think doing the `require(id)` inside that loop isn't going to work, as you'll be partially repopulating the cache as you're clearing it.

You need to clear it out entirely, and let the next incoming route repopulate it.

**Comment by 0cv** [comment]
You're right. I could narrow down the issue to app.use. Something modified outside of Koa feels like to work, but not in Koa. In your version, the middleware is somehow overwritten, but not in my app where even so I do a new app.use with the fresh route, it still keep the previous version. Will try to see/figure out how to deregister/update a middleware...

**Comment by glenjamin** [comment]
Here: https://github.com/glenjamin/ultimate-hot-reloading-example/blob/master/server.js#L28-L31

The middleware here delegates to the real middleware which is "late bound", it always requires the real middleware and passes all the arguments through.

You'll need something like that.

**Comment by 0cv** [comment]
Got it thank you @glenjamin. My mistake was to register the middleware straight (I did the require, then `app.use`) instead of wrapping the require into a function inside `app.use` like you did). I will close the issue, may that help someone else! Thanks again.
