### ISSUE TITLE
Issue when converting to ES6 Module syntax

### ISSUE THREAD

**Issue by andy-mcdonald** [glenjamin/ultimate-hot-reloading-example#20]
First off, thanks for putting together one of the most straightforward examples of 'hot-reloading' via webpack - it's very clean and works just as expected.

My issue is that when I tried to port everything over to ES6 Module syntax, the 'hot-reloading' part worked when making changes however, if I refreshed the browser then the server and client would be out of sync and have to be patched by React.

> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
>  `(client) 2fy1te7zrmk.0">DemoChanged</h1><p data-reacti`
>  `(server) 2fy1te7zrmk.0">Demo</h1><p data-reactid`

It seems my problem is that your approach involves deleting CommonJS modules from the `require.cache` and then requiring them dynamically on each request, and there is currently no equivalent mechanism for ES6 modules.

After some research, it seems as though the best / only option would be to create a separate webpack config for the server code (using `target: 'node'`) and use the `System.import` features of Webpack 2 to dynamically reload the modules at runtime. In which case, where would the `webpackDevMiddleware` and `webpackHotMiddleware` go?

Is an ES6 port something you have considered or attempted and if so, do you have any suggestions?

**Comment by glenjamin** [comment]
As babel compiles ES6 modules into require function calls, I find the simplest way to approach this is to use the require() function in any locations which need to be dynamic.

In this case it is the following two calls:
https://github.com/glenjamin/ultimate-hot-reloading-example/blob/master/server.js#L23
https://github.com/glenjamin/ultimate-hot-reloading-example/blob/master/server.js#L28

Once Node has figured out its ES6 modules story and we know how live bindings will work, this might be doable in a different way.

Making a webpack bundle for the server code is certainly an option, but the goal of this project is explicitly to avoid that, so you'll have to look elsewhere for guidance on how to make that work.

**Comment by andy-mcdonald** [comment]
Cheers for the quick response! Seems that the `store` and `reducers` would also need to implement CommonJS-style `module.exports` since these are also loaded dynamically within the dependency tree for `client/render-server.js`.

I'll try running the server code through webpack and if that doesn't work cleanly, then I might just hold tight until the HMR landscape settles down a bit.

Thanks again for your help!

**Comment by lucasrcosta** [comment]
@andy-mcdonald, I have made the move to ES6 syntax in my fork https://github.com/lucascosta/ultimate-hot-reloading-example, maintaining `require` where needed for the hot reloading.

**Comment by glenjamin** [comment]
I think this thread has demonstrated that there's value in converting to ES6 module syntax for the static parts, to demonstrate the mix - looks like I was wrong in the other PR.

If you fancy sending that change over again @lucascosta I'll get it merged - otherwise I'll try and get around to it myself some time.

Sorry!

**Comment by andy-mcdonald** [comment]
Thanks @lucascosta! After a bit of tinkering, I eventually arrived at an almost identical version to yours and now I'm hot-reloading like a champ! I want to add in some bits and pieces like `react-router` and `Immutable.js` as well as the ability to load images via `webpack` and fetch data asynchronously - I'll post the resulting repo if I feel that it adds value to what is already out there.

@glenjamin - I'm not a fan of the CommonJS `require` / `module.exports` syntax compared to the ES6 equivalent however, in this case it actually enhances readability by establishing a handy convention that makes it is easy to recognize which parts of the app should be loaded dynamically.

Thanks again to both of you. Happy hot loading!
