### ISSUE TITLE
Mongoose bug: schema already defined

### ISSUE THREAD

**Issue by Pitbi** [glenjamin/ultimate-hot-reloading-example#24]
Hello,

i'm very interesting by your approach for hot reload and I try to implement it in one of my application.

I use mongoDB & mongoose, but when i do a modification in my code and the `require.cache` is cleared, I have the following mongoose error: `OverwriteModelError: Cannot overwrite User model once compiled.`.
This error is occurring when a schema is already defined and i defining the schema again. 

My questions are:  
- Do you have solution for this kind of bug?
- If not, what is the best way to reload models?

Thx.

++

**Comment by glenjamin** [comment]
I'm afraid I've never used mongoose, so I don't think I can really help here.

There must be some state somewhere that mongoose is keeping around. You might be better off asking on the mongoose support channels.

**Comment by Pitbi** [comment]
Ok, I suspected the answer :)

Thanks anyway!

**Comment by Pitbi** [comment]
Ok i found the solution. I post it in case someone would be concerned.

It is necessary to reset the mongoose models with `mongoose.models = {}` :

```
watcher.on('ready', function() {
    watcher.on('all', function() {
        console.log('Clearing /server/ module cache from server')
        mongoose.models = {} /*Reset mongoose models*/
        Object.keys(require.cache).forEach(function(id) {
            if (/[\/\\]server[\/\\]/.test(id)) delete require.cache[id]
        })
    })
})
```

++
