### ISSUE TITLE
This isn't hot reloading. This is going to the browser and refreshing

### ISSUE THREAD

**Issue by terencechow** [glenjamin/ultimate-hot-reloading-example#27]
Clearing the `requires.cache` doesn't actually reload your server. You have to go into your browser and refresh the page. That's not hot-reloading at all

**Comment by glenjamin** [comment]
Clearing `require.cache` is not hot reloading, correct.

However, [the actual hot reloading](https://github.com/glenjamin/ultimate-hot-reloading-example/blob/master/webpack.config.js#L20) is in fact hot reloading.

Clearing the cache on the server ensures that if and when you do hit refresh in the browser, the server rendered app is in sync with the latest webpack bundle.
