### ISSUE TITLE
Figure out exactly what file has been changed instead of clear all cache

### ISSUE THREAD

**Issue by namnm** [glenjamin/ultimate-hot-reloading-example#35]
Can we figure out exactly which files has been changed from webpack and clear cache for those files only instead of clear all cache? That would be a lot of nicer I think.

**Comment by nickgcattaneo** [comment]
Webpack's compiler instance, which is exposed in this example, supports an invalid event, which exposes a parameter of the filename. See [event hooks](https://webpack.js.org/api/plugins/compiler/#event-hooks).

e.g.
`compiler.plugin('invalid', fileName => {/* do something with the filename */})`

**Comment by namnm** [comment]
I have just thought about this and I think It's pretty impossible to figure out exactly what files have been changed.
We must flush not only the changed files, but also the files which require the changed files, and so on cursively until the top of the require stack.
So flushing all the files from shared and server folder like what the owner do now is the right way.

Closing...
