### ISSUE TITLE
Has any example about many components and pages?

### ISSUE THREAD

**Issue by zhouwenbin** [glenjamin/ultimate-hot-reloading-example#8]
Has any example about many components and pages?

**Comment by glenjamin** [comment]
I don't have an example of this exactly, although I do hope to have time to add this at some point.

The react router people probably have examples of apps like this - and the hot reloading stuff demoed here should just plug right in.

**Comment by zhouwenbin** [comment]
thanks,i have find one. https://github.com/GetExpert/redux-blog-example
